[[redirects]]
from = "/chatlist"
to = "/index.html"
status = 200

[[redirects]]
from = "/authorization"
to = "/index.html"
status = 200

[[redirects]]
from = "/registration"
to = "/index.html"
status = 200

[[redirects]]
from = "/profile"
to = "/index.html"
status = 200

[[redirects]]
from = "/page404"
to = "/index.html"
status = 200

[[redirects]]
from = "/page500"
to = "/index.html"
status = 200